// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (title, content) VALUES(?, ?) RETURNING id, title, content, createdat
`

type CreateNoteParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Createdat,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, createdat FROM notes WHERE id = ? LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Createdat,
	)
	return i, err
}

const getNotesAbbr = `-- name: GetNotesAbbr :many
SELECT id, title, createdAt FROM notes ORDER BY createdAt DESC
`

type GetNotesAbbrRow struct {
	ID        int64
	Title     string
	Createdat sql.NullTime
}

func (q *Queries) GetNotesAbbr(ctx context.Context) ([]GetNotesAbbrRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotesAbbr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotesAbbrRow
	for rows.Next() {
		var i GetNotesAbbrRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Createdat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
