// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	DeleteNote(ctx context.Context, id int64) error
	GetNote(ctx context.Context, id int64) (Note, error)
	GetNotesAbbr(ctx context.Context) ([]GetNotesAbbrRow, error)
}

var _ Querier = (*Queries)(nil)
